language: c

sudo: false
dist: trusty

cache:
  directories:
    - download

addons:
  apt_packages:
    - libxerces-c-dev
    - libicu-dev
    - libcurl4-openssl-dev
    - autoconf
    - automake
    - libtool

before_install:
  - if test "$(uname -s)" = Darwin; then brew update; fi
  - if test "$(uname -s)" = Darwin; then brew install xerces-c; fi

os:
  - linux
  - osx

env:
  matrix:
    - TOOL="Unix Makefiles" TYPE=Debug MSGLOADER=inmemory TRANSCODER=default
    - TOOL="Ninja" TYPE=Release MSGLOADER=inmemory TRANSCODER=icu

matrix:
  fast_finish: true

script:
  - ./scripts/ci-travis "$TOOL" "$TYPE" "$MSGLOADER" "$TRANSCODER"
